Repository Saeed99Madi/MSS-E-Commarce, pull requests merged in 2023-01, with the labels that each got.

#87 86 client skeleton
  client/components/Footer/index.tsx
  client/components/Header/index.tsx
  client/components/Home/ContactSection/index.tsx
  client/components/Home/FeaturedProducts/index.tsx
  client/components/Home/HeadSection/index.tsx
  client/components/Home/ServicesList/index.tsx
  client/components/Home/TopCategories/index.tsx
  client/interfaces/IProduct.ts
  client/layouts/main.tsx
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/index.tsx
  client/services/ApiService.ts
Labels: waiting review

#88 remove the console log
  client/pages/index.tsx
Labels: waiting review

#91 90 client localisation
  client/i18n.json
  client/locales/ar/home.json
  client/locales/en/home.json
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/index.tsx
  client/tsconfig.json
Labels: Done

#92 add next and there tecknologies in readme file
  README.md
Labels: Done

#93 83 fix categories page
  dashboard/package-lock.json
  dashboard/package.json
  dashboard/src/App.css
  dashboard/src/components/dashboard/Actions/Search/index.tsx
  dashboard/src/components/dashboard/Categories/AddCategories/SelectCategory.tsx
  dashboard/src/components/dashboard/Categories/AddCategories/component.styled.tsx
  dashboard/src/components/dashboard/Categories/AddCategories/index.tsx
  dashboard/src/components/dashboard/Categories/CategoriesList/ListItem.tsx
  dashboard/src/components/dashboard/Categories/CategoriesList/SubLIstItem.tsx
  dashboard/src/components/dashboard/Categories/CategoriesList/component.style.tsx
  dashboard/src/components/dashboard/Categories/CategoriesList/index.tsx
  dashboard/src/components/dashboard/Categories/UpdateCategory/index.tsx
  dashboard/src/components/dashboard/Categories/component.styled.tsx
  dashboard/src/components/dashboard/Categories/index.tsx
  dashboard/src/components/dashboard/Categories/interfaces.styled.ts
  dashboard/src/components/dashboard/DeleteDialog/index.tsx
  dashboard/src/components/dashboard/Products/AddProduct/SelectCategories/index.tsx
  dashboard/src/components/dashboard/ToastContainer/index.tsx
  dashboard/src/hooks/getCategory.ts
  dashboard/src/hooks/useForm.ts
  dashboard/src/interfaces/ICategories.ts
  dashboard/src/layouts/DashboardLayout/style.css
  src/controllers/CategoriesController.ts
  src/routes/categories.ts
Labels: waiting review

#97 lead section Component
  client/components/Home/HeadSection/components.styled.tsx
  client/components/Home/HeadSection/index.tsx
  client/pages/index.tsx
  client/public/assets/background.png
  client/public/assets/map.png
Labels: Done

#95 94 Layouts header landing page
  client/components/Header/Actions/ActionButtons/index.tsx
  client/components/Header/Actions/index.tsx
  client/components/Header/Logo/index.tsx
  client/components/Header/NavHeader/index.tsx
  client/components/Header/components.styled.tsx
  client/components/Header/index.tsx
  client/config/index.ts
  client/i18n.json
  client/interfaces/ICategory.ts
  client/layouts/main.tsx
  client/locales/ar/home.json
  client/locales/en/home.json
  client/locales/fr/home.json
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/pages/index.tsx
  client/services/ApiService.ts
  src/images/settings/Group.png
Labels: Done

#101 100 services section
  client/components/Home/ServicesList/components.styled.tsx
  client/package-lock.json
  client/package.json
Labels: under development

#102 icon
  client/components/Home/ServicesList/index.tsx
  client/pages/index.tsx
Labels: Done

#99 98 featured products
  client/components/Home/FeaturedProducts/components.styled.tsx
  client/components/Home/FeaturedProducts/index.tsx
  client/pages/index.tsx
  client/services/ApiService.ts
Labels: waiting review

#103 make services section responsive
  client/components/Home/ServicesList/components.styled.tsx
Labels: waiting review

#104 make transition for responsive
  client/components/Home/ServicesList/components.styled.tsx
Labels: waiting review

#106 105 top categories
  client/components/Home/TopCategories/components.styled.tsx
  client/components/Home/TopCategories/index.tsx
  client/pages/index.tsx
Labels: waiting review

#114 fix spacing in category page
  dashboard/src/components/dashboard/Categories/CategoriesList/component.style.tsx
Labels: waiting review

#115 109 responsive lead section
  client/components/Home/HeadSection/components.styled.tsx
  client/components/Home/HeadSection/index.tsx
Labels: waiting review

#108 107 contact section
  client/components/Home/ContactSection/components.styled.tsx
  client/components/Home/ContactSection/index.tsx
  client/pages/index.tsx
  client/public/assets/contact.png
  client/public/assets/whatsapp.png
Labels: waiting review

#118 make the products section srcrollable
  dashboard/src/components/dashboard/Actions/Search/index.tsx
  dashboard/src/components/dashboard/Products/index.tsx
  dashboard/src/components/dashboard/components.styled.tsx
  dashboard/src/hooks/getAllCategories.ts
  src/controllers/CategoriesController.ts
  src/db/seeds.json
  src/routes/categories.ts
Labels: waiting review

#119 Responsive Footer
  client/components/Footer/components.styled.tsx
  client/components/Footer/index.tsx
  client/components/Home/ContactSection/components.styled.tsx
  client/components/Home/FeaturedProducts/components.styled.tsx
  client/components/Home/TopCategories/components.styled.tsx
Labels: waiting review

#121 120 fix home style
  client/components/Home/HeadSection/components.styled.tsx
  client/components/Home/HeadSection/index.tsx
  client/components/Home/ServicesList/components.styled.tsx
  client/components/Home/ServicesList/index.tsx
Labels: waiting review

#123 fix Bug publish and unpublish
  dashboard/src/components/dashboard/Actions/MarkAs/index.tsx
Labels: waiting review

#132 create product name section
  client/components/Product/ProductFeatures/index.tsx
  client/components/Product/ProductName/ProductDetails.tsx
  client/components/Product/ProductName/ProductImages.tsx
  client/components/Product/ProductName/index.tsx
  client/components/Product/RelatedProducts/index.tsx
  client/components/Product/components.styled.tsx
  client/pages/index.tsx
  client/pages/product/index.tsx
  client/utils/devices/index.ts
  src/controllers/CategoriesController.ts
Labels: Done, waiting review

#129 solve Scrolling Bug in Dashboard
  dashboard/src/App.css
  dashboard/src/components/dashboard/Actions/MarkAs/index.tsx
  dashboard/src/components/dashboard/Products/Card/index.tsx
  dashboard/src/components/dashboard/Products/index.tsx
  dashboard/src/components/dashboard/components.styled.tsx
Labels: waiting review

#133 fix dashboard scroll issue
  dashboard/src/App.css
Labels: Done

#136 create products feature section
  client/components/Product/ProductFeatures/ListItem.tsx
  client/components/Product/ProductFeatures/index.tsx
  client/components/Product/components.styled.tsx
  client/public/assets/rec-group.png
Labels: waiting review

#137 create related product section
  client/components/Product/RelatedProducts/ProductCard.tsx
  client/components/Product/RelatedProducts/index.tsx
  client/components/Product/components.styled.tsx
Labels: Done

#141 138 edit product route
  src/controllers/ProductController.ts
  src/db/connection.ts
  src/models/Product.ts
  src/routes/products.ts
Labels: waiting review

#143 lintier all files and handle success and failed status
  dashboard/src/components/dashboard/Actions/Search/index.tsx
  dashboard/src/components/dashboard/Categories/AddCategories/index.tsx
  dashboard/src/components/dashboard/Categories/CategoriesList/ListItem.tsx
  dashboard/src/components/dashboard/Categories/CategoriesList/component.style.tsx
  dashboard/src/components/dashboard/Categories/CategoriesList/index.tsx
  dashboard/src/components/dashboard/Categories/UpdateCategory/index.tsx
  dashboard/src/components/dashboard/Categories/component.styled.tsx
  dashboard/src/components/dashboard/Login/index.tsx
  dashboard/src/components/dashboard/Products/AddProduct/AttriputeForms/AttriputeCard/index.tsx
  dashboard/src/components/dashboard/Products/AddProduct/UploadProductFiles/index.tsx
  dashboard/src/components/dashboard/Products/AddProduct/index.tsx
  dashboard/src/components/dashboard/Products/Card/index.tsx
  dashboard/src/components/dashboard/Products/EditProduct/UploadProductFiles/index.tsx
  dashboard/src/components/dashboard/Products/EditProduct/index.tsx
  dashboard/src/context/AuthContext.tsx
  dashboard/src/helpers/AttriputeReducer.ts
  dashboard/src/pages/dashboard.tsx
Labels: waiting review

#144 142 full check products components
  dashboard/src/components/dashboard/Actions/MarkAs/index.tsx
  dashboard/src/components/dashboard/ConfermAction/index.tsx
  dashboard/src/components/dashboard/Products/AddProduct/index.tsx
  dashboard/src/components/dashboard/Products/Card/index.tsx
  dashboard/src/components/dashboard/Products/EditProduct/index.tsx
  dashboard/src/context/DashboardContext.tsx
  dashboard/src/interfaces/IDashboardContext.ts
  dashboard/src/pages/dashboard.tsx
  src/controllers/ProductController.ts
Labels: waiting review

#145 130 contact page
  client/components/Contact/ContactByForm.tsx
  client/components/Contact/ContactByWhatsApp.tsx
  client/components/Contact/components.styled.tsx
  client/components/Contact/index.tsx
  client/components/Home/ContactSection/components.styled.tsx
  client/hooks/useForm.ts
  client/package-lock.json
  client/package.json
  client/pages/contact/index.tsx
  client/public/assets/contact-whatsapp.png
  client/public/assets/form-background.png
  client/public/assets/form.png
  client/public/assets/logo.png
Labels: waiting review

#155 130 contact page
  client/components/Contact/ContactByForm.tsx
  client/components/Contact/ContactByWhatsApp.tsx
  client/components/Contact/components.styled.tsx
  client/components/Contact/index.tsx
  client/hooks/useForm.ts
  client/package-lock.json
  client/package.json
  client/pages/contact/index.tsx
  client/public/assets/contact-whatsapp.png
  client/public/assets/logo.png
Labels: waiting review

#147 146 improve services management "Dashboard"
  dashboard/src/components/dashboard/Services/Actions/MarkAs/index.tsx
  dashboard/src/components/dashboard/Services/Card/index.tsx
  dashboard/src/components/dashboard/Services/EditService/UploadServiceFiles/index.tsx
  dashboard/src/components/dashboard/Services/EditService/index.tsx
  dashboard/src/components/dashboard/Services/index.tsx
  dashboard/src/context/DashboardContext.tsx
  dashboard/src/interfaces/IDashboardContext.ts
  dashboard/src/interfaces/IService.ts
Labels: waiting review

#156 130 contact page
  client/components/Contact/ContactByForm.tsx
  client/components/Contact/ContactByWhatsApp.tsx
Labels: waiting review

#150 80 contacts managemnt dashboard
  dashboard/src/App.tsx
  dashboard/src/components/dashboard/Contacts/ContactsList/ListItem.tsx
  dashboard/src/components/dashboard/Contacts/ContactsList/component.style.tsx
  dashboard/src/components/dashboard/Contacts/ContactsList/index.tsx
  dashboard/src/components/dashboard/Contacts/ContactsList/showContact.tsx
  dashboard/src/components/dashboard/Contacts/index.tsx
  dashboard/src/context/DashboardContext.tsx
  dashboard/src/interfaces/IContact.ts
  dashboard/src/interfaces/IDashboardContext.ts
  src/controllers/ContactController.ts
Labels: waiting review

#149 create update Services Route
  src/controllers/ServicesController.ts
  src/routes/services.ts
Labels: waiting review
